### PR TITLE
0.16.0

### PR DESCRIPTION
**Pull request by gnestor**
Upgrade to juypterlab@0.16.0

### CODE REVIEW

**Comment by ellisonbg** [comment]
Which of these PRs can I merge and in what order?

**Comment by gnestor** [comment]
1. Add `.json` extension
2. 0.16.0
3. I'm still working on Vega/VegaLite display classes

**Comment by gnestor** [comment]
I could also use your eyes at https://github.com/jupyterlab/mimerender-cookiecutter/pull/45 👍

**Comment by ellisonbg** [comment]
Great!

**Pull request merged**
